BOT_TOKEN: "44444444444444:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
NoSSD_PATCH: "/home/bds89/Документы/nossd"
NoSSD_PARAMS: "-a xch18s44l93zegl3p3awkhfdwy5hhuj74wvkuzndvasjgkx7w37s4dsqpumnje -c 10 -w bds89 -d,p /media/bds89/Новый том1/test"
PASSWORD: "12345"
RUN_AT_STARTUP: False
SUDO_PASS: "0"
SLAVE_PC: False
NODES:
  - 192.168.0.138
  - 192.168.0.55
