BOT_TOKEN: "4444444444:xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
PASSWORD: "12345"
NoSSD_PATCH: "/home/bds89/Документы/nossd"
NoSSD_PARAMS: "-a xch18s44l93zegl3p3awkhfdwy5hhuj74wvkuzndvasjgkx7w37s4dsqpumnje -c 15 -w bds89 -d,p /media/bds89/Новый том1/test"
RUN_AT_STARTUP: False
SUDO_PASS: "0"
SLAVE_PC: False
NODES:
  - 192.168.0.55
  - 192.168.0.54
  - 192.168.0.53
  - 192.168.0.52
  - 192.168.0.138
